name: GitHub Actions Multiple jobs demo
run-name: GitHub Actions Multiple jobs demo
on: [push]
jobs:
  job-01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List contents in the workspace
        run: ls -al ${{ github.workspace }}     
  job-02:
    needs: job-01
    runs-on: ubuntu-latest
    steps:
      - name: List contents in the workspace
        run: ls -al ${{ github.workspace }}     
