name: GitHub Actions Multi Jobs Demo
run-name: GitHub Actions Multi Jobs Demo
on: [push]
jobs:
  job-01:
    runs-on: ubuntu-latest
    steps:
    - name: Create a temp file
      run: echo Hello > hello.txt
  job-02:
    runs-on: ubuntu-latest
    steps:
    - name: Read temp file
      run: cat ${{ github.workspace }}/hello.txt
