name: GitHub Actions Events Demo
run-name: GitHub Actions Events
on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    types: [opened, closed]
jobs:
  Get-Environment-Variables:
    runs-on: ubuntu-latest
    steps:
    - name: Read environment variables
      run: |
        echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
        echo "GITHUB_SHA: ${{ github.sha }}"
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
    - name: Display base_ref and head_ref
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
      run: |
        echo "This event is a pull request"
        echo "GITHUB_BASE_REF: ${{ github.base_ref }}"
        echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
