name: GitHub Actions Multi Jobs Demo
run-name: GitHub Actions Multi Jobs Demo
on: [push]
jobs:
  job-01:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SCM
      uses: actions/checkout@v3
    - name: list workspace contents
      run: ls -al ${{ github.workspace }}  
  job-02:
    runs-on: ubuntu-latest
    steps:
    - name: list workspace contents
      run: ls -al ${{ github.workspace }} 
