name: Cancelling a workflow
run-name: Cancelling a workflow
on: [push]
jobs:
  job-01:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: print job id
        run: |
          echo ${{ github.job }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
  job-02:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
