name: GitHub Actions Events Demo
run-name: GitHub Actions Events
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
jobs:
  Get-Environment-Variables:
    runs-on: ubuntu-latest
    steps:
    - name: Read environment variables
      run: |
        echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
        echo "GITHUB_SHA: ${{ github.sha }}"
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
        echo "GITHUB_BASE_REF: ${{ github.base_ref }}"
        echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
